# .travis.yml

language: android

#branches:
#  only:
#    - master
#    - develop

install:
   - bundle install

script:
   - ./gradlew assembleDebug
   - bundle exec danger

cache:
    - bundler
    directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

#before_script:
#    bundle exec danger
